### PR TITLE
Remove uneven parenthesis

### LINKED ISSUE #14: Unbalanced parenthesis
I can't load this package because of unbalanced parenthesis error. Have no time to trace it to certain commit, but parser said its execute-project-target function.

### PR DESCRIPTION
**Pull request by jumper047**
Fix #14

### CODE REVIEW

**Comment by patrickt** [comment]
So sorry to have introduced this in #11. Totally my fault. This looks good to merge. I can contribute some CI checks that will ensure this won’t happen again.

**Comment by jumper047** [comment]
In fact I made same mistake some time ago in my own package:)

**Comment by Olivia5k** [comment]
This was fixed in #16. My bad for not noticing earlier. I need to set up my notifications better or something.

Thanks anyways!

**Comment by jumper047** [comment]
Your apologies sounds like straight.el promotion:)))

**Comment by jimeh** [comment]
@jumper047 not intentionally, but like, it's pretty sweet ;)... lol

**Pull request closed without merging**
